### ISSUE TITLE
Demo: Link examples

### ISSUE THREAD

**Issue by koppor** [GuillaumeFalourd/useful-actions#724]
Thank you for providing examples here (e.g., https://github.com/GuillaumeFalourd/useful-actions/issues/3). I found them by accident. 

Could you please link them from [README.md](https://github.com/GuillaumeFalourd/useful-actions#useful-actions)?

**Comment by GuillaumeFalourd** [comment]
Hi @koppor , I'm not sure about what you're asking.
You want me to share the workflow which opened the PR you linked in the ISSUE on the README file?

**Comment by koppor** [comment]
Yes. That's what I meant. Currently, the action yml files are linked above the text. They lead to example runs. However, the concrete actions taken (e.g., commenting) are not linked. These are interesting for me to see the effects of the action.

**Comment by GuillaumeFalourd** [comment]
What I tried to shared in the README file is what operation each action could perform. For example, the commenting action uses the [github-script](https://github.com/GuillaumeFalourd/useful-actions/blob/main/.github/workflows/github-script.yml) workflow. You want me to share this `github-script `workflow file along with the workflow runs using the action, on the README file then, am I right?

**Comment by koppor** [comment]
No worries, maybe it is good enough as it is.

I was confused about the white space and that the white space is not aligned with information blocks belonging together:

![image](https://github.com/GuillaumeFalourd/useful-actions/assets/1366654/1f621d4c-bdb1-4425-a926-3434456ef5b0)

In the screenshot above, the "passing" label belongs to the NEXT paragraph, not to the previous one. One has to read the description inside that label, too.

I was about to write the following, but after some thought, it is overcomplicating things.

```markdown
### Action title

<description>

- Workflow file: <link>
- Example comment: <link> (if matching the action)
```

**Comment by GuillaumeFalourd** [comment]
Ok, I understand the confusion now, thank you for explaining. Now, if you wish to do this update on the README file during the Hacktoberfest, no problem 😄
