### ISSUE TITLE
Add ".take" action

### ISSUE THREAD

**Issue by koppor** [GuillaumeFalourd/useful-actions#995]
https://github.com/bdougie/take-action

A user can post the message ".take" and then they is assigned.

**Comment by GuillaumeFalourd** [comment]
Hi @koppor , how are you doing? Thank you for opening this issue :)

Would you like to contribute to the repository adding this new action by following the repository [contribution guidelines](https://github.com/GuillaumeFalourd/useful-actions/blob/main/CONTRIBUTING.md)?

**Comment by koppor** [comment]
https://github.com/takanome-dev/assign-issue-action worked better here - even though there are more issues.

The "github-actions" bot should have closed this as "not planned" instead of "completed" though.
